# Pre-commit hooks library for GenAI code validation and security
# Supports: Node.js, Angular, React, Python, TypeScript, Java, Terraform, CloudFormation

# =============================================================================
# LINTING AND CODE QUALITY HOOKS
# =============================================================================

# Python linting and formatting
- id: python-black
  name: Black (Python formatter)
  entry: black
  language: python
  types: [python]
  require_serial: false

- id: python-flake8
  name: Flake8 (Python linter)
  entry: flake8
  language: python
  types: [python]
  require_serial: false

- id: python-isort
  name: isort (Python import sorter)
  entry: isort
  language: python
  types: [python]
  require_serial: false

- id: python-mypy
  name: MyPy (Python type checker)
  entry: mypy
  language: python
  types: [python]
  require_serial: false

# JavaScript/TypeScript/Node.js linting
- id: eslint
  name: ESLint (JavaScript/TypeScript linter)
  entry: hooks/eslint.sh
  language: script
  files: \.(js|jsx|ts|tsx)$
  require_serial: false

- id: prettier
  name: Prettier (Code formatter)
  entry: hooks/prettier.sh
  language: script
  files: \.(js|jsx|ts|tsx|json|css|scss|md|html)$
  require_serial: false

- id: typescript-check
  name: TypeScript compiler check
  entry: hooks/tsc-check.sh
  language: script
  files: \.tsx?$
  require_serial: false

# Angular specific
- id: angular-lint
  name: Angular linting
  entry: hooks/angular-lint.sh
  language: script
  files: \.(ts|html|scss|css)$
  pass_filenames: false
  require_serial: false

# Java linting
- id: java-checkstyle
  name: Java Checkstyle
  entry: hooks/java-checkstyle.sh
  language: script
  files: \.java$
  require_serial: false

- id: java-spotbugs
  name: Java SpotBugs
  entry: hooks/java-spotbugs.sh
  language: script
  files: \.java$
  require_serial: false

# Infrastructure as Code
- id: terraform-fmt
  name: Terraform format
  entry: terraform fmt
  language: system
  files: \.tf$
  require_serial: false

- id: terraform-validate
  name: Terraform validate
  entry: hooks/terraform-validate.sh
  language: script
  files: \.tf$
  require_serial: false

- id: terraform-tflint
  name: TFLint (Terraform linter)
  entry: tflint
  language: system
  files: \.tf$
  require_serial: false

- id: cloudformation-validate
  name: CloudFormation template validation
  entry: hooks/cfn-validate.sh
  language: script
  files: \.(yaml|yml|json)$
  require_serial: false

# =============================================================================
# SECURITY SCANNING HOOKS
# =============================================================================

# Secret scanning
- id: detect-secrets
  name: Detect secrets
  entry: detect-secrets-hook
  language: python
  types: [text]
  require_serial: false

- id: truffhog
  name: TruffleHog secret scanner
  entry: hooks/truffhog.sh
  language: script
  types: [text]
  require_serial: false

# Custom security checks for GenAI code
- id: hardcoded-urls
  name: Detect hardcoded URLs
  entry: hooks/detect_hardcoded_urls.py
  language: python
  types: [text]
  require_serial: false

- id: hardcoded-credentials
  name: Detect hardcoded credentials
  entry: hooks/detect_hardcoded_credentials.py
  language: python
  types: [text]
  require_serial: false

- id: genai-security-check
  name: GenAI-specific security validation
  entry: hooks/genai_security_check.py
  language: python
  types: [text]
  require_serial: false

# Vulnerability scanning
- id: safety-python
  name: Safety (Python dependency vulnerability scanner)
  entry: safety
  language: python
  pass_filenames: false
  files: requirements.*\.txt$
  require_serial: false

- id: npm-audit
  name: npm audit (Node.js vulnerability scanner)
  entry: hooks/npm-audit.sh
  language: script
  files: package\.json$
  pass_filenames: false
  require_serial: false

- id: yarn-audit
  name: Yarn audit (Node.js vulnerability scanner)
  entry: hooks/yarn-audit.sh
  language: script
  files: package\.json$
  pass_filenames: false
  require_serial: false

# SAST scanning
- id: bandit
  name: Bandit (Python security linter)
  entry: bandit
  language: python
  types: [python]
  args: ['-r', '.']
  require_serial: false

- id: semgrep
  name: Semgrep (Multi-language SAST)
  entry: hooks/semgrep.sh
  language: script
  types: [text]
  require_serial: false

# =============================================================================
# GENERAL VALIDATION HOOKS
# =============================================================================

# File format validation
- id: check-xml
  name: Check XML syntax
  entry: hooks/check_xml.py
  language: python
  files: \.xml$

# Note: For standard file validation hooks like check-yaml, check-json, 
# trailing-whitespace, end-of-file-fixer, etc., use the official pre-commit-hooks:
# 
# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.4.0
#     hooks:
#       - id: check-yaml
#       - id: check-json
#       - id: trailing-whitespace
#       - id: end-of-file-fixer
#       - id: check-merge-conflict
#       - id: mixed-line-ending
#       - id: check-toml

# License and copyright validation
- id: check-license
  name: Check for license headers
  entry: hooks/check_license.py
  language: python
  types: [text]
  require_serial: false

# Note: For large file detection, use the official pre-commit-hooks:
# - id: check-added-large-files
#   args: [--maxkb=1000]

# Docker security
- id: dockerfile-lint
  name: Dockerfile linting
  entry: hooks/dockerfile-lint.sh
  language: script
  files: Dockerfile

# =============================================================================
# .NET HOOKS
# =============================================================================

- id: dotnet-format
  name: .NET code formatter
  entry: hooks/dotnet-format.sh
  language: script
  files: \.(cs|vb|fs)$
  require_serial: false

- id: dotnet-test
  name: .NET test runner
  entry: hooks/dotnet-test.sh
  language: script
  files: \.(cs|vb|fs|csproj|sln)$
  require_serial: false

- id: dotnet-security-scan
  name: .NET security scanner
  entry: hooks/dotnet-security-scan.py
  language: python
  files: \.(cs|vb|fs|config|json)$
  require_serial: false

# =============================================================================
# GO HOOKS
# =============================================================================

- id: go-fmt
  name: Go code formatter
  entry: hooks/go-fmt.sh
  language: script
  files: \.go$
  require_serial: false

- id: go-lint
  name: Go linter with security checks
  entry: hooks/go-lint.sh
  language: script
  files: \.go$
  require_serial: false

- id: go-security-scan
  name: Go security scanner
  entry: hooks/go-security-scan.sh
  language: script
  files: \.go$
  require_serial: false

# =============================================================================
# ANSIBLE HOOKS
# =============================================================================

- id: ansible-lint
  name: Ansible linting
  entry: hooks/ansible-lint.sh
  language: script
  files: \.(yml|yaml)$
  require_serial: false

- id: ansible-syntax-check
  name: Ansible syntax validation
  entry: hooks/ansible-syntax-check.sh
  language: script
  files: \.(yml|yaml)$
  require_serial: false

- id: ansible-security-scan
  name: Ansible security scanner
  entry: hooks/ansible-security-scan.py
  language: python
  files: \.(yml|yaml|cfg)$
  require_serial: false
