"""
Pre-commit hooks library for GenAI code validation and security.

This package provides a comprehensive collection of pre-commit hooks designed to
validate and secure code generated by AI tools like GitHub Copilot, ChatGPT,
and other GenAI assistants.
"""

__version__ = "1.0.1"
__author__ = "TriaFed"
__email__ = "info@triafed.com"
__description__ = "Pre-commit hooks library for GenAI code validation and security"
